### ISSUE TITLE
Segmentation Error

### ISSUE THREAD

**Issue by hgaertner22** [tomography/xlearn#12]
Using Python 3.6 on Windows, I tried to use the segmentation example (https://github.com/tomography/xlearn/blob/master/doc/demo/segmentation.py) so that I could use multiple training images to identify features in an image. However, when I try this I get an error "TypeError: Expected int32, got 8.0 of type 'float' instead" (Full error message below). I was wondering if anyone had suggestions as to how to fix this? Thank you

runfile('C:/Users/Hannah/Downloads/python programs/xlearn_seg2.py', wdir='C:/Users/Hannah/Downloads/python programs')
Traceback (most recent call last):

  File "<ipython-input-7-96e7e5cb8f54>", line 1, in <module>
    runfile('C:/Users/Hannah/Downloads/python programs/xlearn_seg2.py', wdir='C:/Users/Hannah/Downloads/python programs')

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\spyder\utils\site\sitecustomize.py", line 705, in runfile
    execfile(filename, namespace)

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\spyder\utils\site\sitecustomize.py", line 102, in execfile
    exec(compile(f.read(), filename, 'exec'), namespace)

  File "C:/Users/Hannah/Downloads/python programs/xlearn_seg2.py", line 34, in <module>
    mdl=seg_train(imgx, imgy, batch_size=batch_size, nb_epoch=nb_epoch, nb_gpu=nb_gpu)

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\xlearn-0.2.0-py3.6.egg\xlearn\segmentation.py", line 138, in seg_train
    mdl = model_choose(patch_size, patch_size, nb_conv, size_conv, nb_down, nb_gpu)

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\xlearn-0.2.0-py3.6.egg\xlearn\segmentation.py", line 69, in model_choose
    mdl = transformer2(ih, iw, nb_conv, size_conv, nb_gpu)

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\xlearn-0.2.0-py3.6.egg\xlearn\models.py", line 161, in transformer2
    fc1 = Reshape((ih / 4, iw / 4, 1))(fc1)

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\tensorflow\python\keras\_impl\keras\engine\topology.py", line 258, in __call__
    output = super(Layer, self).__call__(inputs, **kwargs)

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\tensorflow\python\layers\base.py", line 652, in __call__
    outputs = self.call(inputs, *args, **kwargs)

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\tensorflow\python\keras\_impl\keras\layers\core.py", line 401, in call
    return K.reshape(inputs, (K.shape(inputs)[0],) + self.target_shape)

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\tensorflow\python\keras\_impl\keras\backend.py", line 1986, in reshape
    return array_ops.reshape(x, shape)

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\tensorflow\python\ops\gen_array_ops.py", line 5184, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 513, in _apply_op_helper
    raise err

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\tensorflow\python\framework\ops.py", line 1022, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\tensorflow\python\ops\array_ops.py", line 1001, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\tensorflow\python\ops\array_ops.py", line 963, in _autopacking_helper
    constant_op.constant(elem, dtype=dtype, name=str(i)))

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\tensorflow\python\framework\constant_op.py", line 212, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 413, in make_tensor_proto
    _AssertCompatible(values, dtype)

  File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\tensorflow\python\framework\tensor_util.py", line 328, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))

TypeError: Expected int32, got 8.0 of type 'float' instead.

**Comment by XYangXRay** [comment]
The xlearn coded and tested under linux and python 2.  I am not familiar with this python 3 issues of the data type.

**Comment by decarlof** [comment]
can you confirm that xlearn_seg2.py line 1 is the import of xlearn?
xlearn_seg2.py", line 34 shows the same error. I think all the divide operation whose results is handled as an int in a follow up call function should be replaced from float division ('/') into floor division ('//').

**Comment by decarlof** [comment]
I was able to run the test on python 3.6 on linux. @hgaertner22 may you please share xlearn_seg2.py. Best if you share it by creating a new github repository under [your github](https://github.com/hgaertner22?tab=repositories)

**Comment by decarlof** [comment]
@hgaertner22 can you also try to run the test running xlearn/doc/demo/segmentation.py ?

**Comment by hgaertner22** [comment]
When I tried running xlearn/doc/demo/segmentation.py I got the same error that I do when I try to run my version xlearn_seg2.py ("Expected int32, got '4.0' of type 'float' instead").

I have uploaded xlearn_seg2.py to my github at https://github.com/hgaertner22/Segmentation

**Comment by decarlof** [comment]
I found a few threads reporting this error as a python 2 vs python 3 issue (see [here](https://github.com/tensorflow/models/issues/3661)). I suspect there is a divide somewhere generating a float that is then passed to a function only accepting integer. Can this be the

```
File "C:\Users\Hannah\Downloads\WinPython\python-3.6.5.amd64\lib\site-packages\xlearn-0.2.0-py3.6.egg\xlearn\models.py", line 161, in transformer2
fc1 = Reshape((ih / 4, iw / 4, 1))(fc1)
```

?

**Comment by XYangXRay** [comment]
Yes, it should be the issue. This reshape needs int data type. Python 3 may generate float from the divide. Please change fc1 = Reshape((ih / 4, iw / 4, 1))(fc1) to be fc1 = Reshape((ih / /4, iw // 4, 1))(fc1) to see.
