### ISSUE TITLE
segmentation.py fails to run on test data

### ISSUE THREAD

**Issue by decarlof** [tomography/xlearn#8]
python segmentation.py 

Using TensorFlow backend.
Traceback (most recent call last):
  File "segmentation.py", line 18, in <module>
    mdl = seg_train(imgx, imgy, batch_size = batch_size, nb_epoch = nb_epoch, nb_down = nb_down, nb_gpu = nb_gpu)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/xlearn-0.2.0-py3.6.egg/xlearn/segmentation.py", line 138, in seg_train
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/xlearn-0.2.0-py3.6.egg/xlearn/segmentation.py", line 67, in model_choose
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/xlearn-0.2.0-py3.6.egg/xlearn/models.py", line 235, in transformer3_pooling
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 314, in __call__
    output = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 717, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/core.py", line 420, in call
    (array_ops.shape(inputs)[0],) + self.target_shape)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6113, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 513, in _apply_op_helper
    raise err
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1034, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 996, in _autopacking_helper
    constant_op.constant(elem, dtype=dtype, name=str(i)))
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 432, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 343, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got 4.0 of type 'float' instead.
(test) bash-4.2$ python segmentation.py 
Using TensorFlow backend.
Traceback (most recent call last):
  File "segmentation.py", line 21, in <module>
    mdl = seg_train(imgx, imgy, batch_size = batch_size, nb_epoch = nb_epoch, nb_down = nb_down, nb_gpu = nb_gpu)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/xlearn-0.2.0-py3.6.egg/xlearn/segmentation.py", line 138, in seg_train
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/xlearn-0.2.0-py3.6.egg/xlearn/segmentation.py", line 67, in model_choose
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/xlearn-0.2.0-py3.6.egg/xlearn/models.py", line 235, in transformer3_pooling
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/engine/base_layer.py", line 314, in __call__
    output = super(Layer, self).__call__(inputs, *args, **kwargs)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/layers/base.py", line 717, in __call__
    outputs = self.call(inputs, *args, **kwargs)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/keras/_impl/keras/layers/core.py", line 420, in call
    (array_ops.shape(inputs)[0],) + self.target_shape)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 6113, in reshape
    "Reshape", tensor=tensor, shape=shape, name=name)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 513, in _apply_op_helper
    raise err
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 510, in _apply_op_helper
    preferred_dtype=default_dtype)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1104, in internal_convert_to_tensor
    ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1034, in _autopacking_conversion_function
    return _autopacking_helper(v, inferred_dtype, name or "packed")
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 996, in _autopacking_helper
    constant_op.constant(elem, dtype=dtype, name=str(i)))
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py", line 214, in constant
    value, dtype=dtype, shape=shape, verify_shape=verify_shape))
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 432, in make_tensor_proto
    _AssertCompatible(values, dtype)
  File "/local/decarlo/conda/anaconda/envs/test/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py", line 343, in _AssertCompatible
    (dtype.name, repr(mismatch), type(mismatch).__name__))
TypeError: Expected int32, got 4.0 of type 'float' instead.

**Comment by ZeliangSu** [comment]
I think it's still a problem of dtype. Can you try to explicit type of ih and iw by replacing int(ih)/8 and int(iw)/8 at 235? Or int(ih/8) and int(iw/8)

**Comment by decarlof** [comment]
@ZeliangSu thanks this fixes the error, I think I see it because I am running on python 3.6 which is tighter on different types operation
